#!/bin/bash
# Quick activation script for SHAP microservice environment
echo "🔌 Activating SHAP microservice environment..."
source "venv313/bin/activate"
echo "✅ Environment activated!"
echo "📍 Current directory: $(pwd)"
echo "🐍 Python version: $(python --version)"
echo ""
echo "🚀 Available commands:"
echo "  python setup_arcgis_extraction.py     # Configure data extraction"
echo "  python extract_arcgis_data.py         # Extract ArcGIS data"
echo "  python update_data_pipeline.py        # Process data and train model"
echo "  python app.py                         # Start SHAP microservice"
echo ""
echo "📋 Quick start workflow:"
echo "  1. python setup_arcgis_extraction.py"
echo "  2. python extract_arcgis_data.py --config config/feature_services.json"
echo "  3. python update_data_pipeline.py --use-existing"
echo "" 