# HRB SHAP Microservice
services:
  - type: web
    name: hrb-microservice
    env: python
    plan: starter
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 180
    buildCommand: pip install -r requirements_py313.txt && chmod +x ./render_pre_deploy.sh && ./render_pre_deploy.sh
    envVars:
      - key: MODEL_PATH
        value: "/app/models"
      - key: DATA_PATH
        value: "/app/data"
      - key: SERVICE_NAME
        value: "HRB SHAP Microservice"
