# HRB SHAP Microservice
services:
  - type: web
    name: hrb-microservice
    env: python
    plan: starter
    pythonVersion: "3.11.7"
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 180
    buildCommand: |
      pip install --upgrade pip && \
      pip install --only-binary=all --no-cache-dir -r requirements.txt
    envVars:
      - key: MODEL_PATH
        value: "/app/models"
      - key: DATA_PATH
        value: "/app/data"
      - key: SERVICE_NAME
        value: "HRB SHAP Microservice"
